version: 2.1

orbs:
  slack: usertech/circleci-slack-orb@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

executors:
  cimg:
    docker:
      - image: cimg/base:stable
  alpine:
    # This image contains both CURL and JQ
    docker:
      - image: dwdraju/alpine-curl-jq

jobs:
  integration-test-templates:
    parameters:
      runner:
        type: executor
        default: cimg
    executor: <<parameters.runner>>
    steps:
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Current Job: $CIRCLE_JOB"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "This test will @ a normal user, a user ID, and normal group name: <@U8C9ETTUG>, @orbs, @gabriel"
                  }
                }
              ]
            }

      - run:
          name: Verify SLACK_JOB_STATUS is written
          command: |
            grep "pass" /tmp/SLACK_JOB_STATUS

      - slack/notify:
          template: deafult_fail_1
          mentions: "@orbs"
          event: always

      - slack/notify:
          template: default_pass_1
          event: always

      - slack/notify:
          template: basic_on_hold_1
          event: always

      - slack/notify:
          event: pass
          custom: >
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Sample link using environment variable in markdown <${CIRCLE_BUILD_URL}|LINK >"
                  }
                }
              ]
            }

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148,SC2001,SC1091,SC2086,SC2116,SC2046,SC2005,SC2002
          shell: sh
      - bats/run:
          path: ./src/tests
      - orb-tools/pack:
          use-orb-pack: true
      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      - orb-tools/publish-dev:
          orb-name: usertech/circleci-slack-orb
          context: orb-publishing
          requires:
            - hold-for-dev-publish
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-templates:
          context: SLACK_SECRETS_TEST
          matrix:
            parameters:
              runner: [cimg, alpine]

  integration-test-templates:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-templates
      - orb-tools/dev-promote-prod-from-commit-subject:
          context: orb-publishing
          orb-name: usertech/circleci-slack-orb
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test-templates
          filters:
            branches:
              only:
                - master
